### ISSUE TITLE
Плохо читаемый код

### ISSUE THREAD

**Issue by Dekart-hub** [Mexech/tech_prog_6#1]
Плохо читается такая строка и не сразу понятно для чего она:
https://github.com/Mexech/tech_prog_6/blob/fab98ade7c0b492f4c25454a11b896c7c9d6cfbe/main.cpp#L45

Возможно стоит переносить на новые строки и использовать std::endl для форматирования. Так получится более читабельно
```c++  
    cout << "Type command:" << endl
            << "1 - add new worker" << endl
            << "2 - display workers" << endl
            << "3 - edit worker" << endl
            << "4 - remove worker" << endl
            << "5 - display workers with specified work experience" << endl
            << "6 - exit" << endl;
```

**Comment by Mexech** [comment]
НЕ ПРАВДА!!!!!!!!!! Код идеален.
